export function buildCircuitBreakerPrompt(
	failureCount: number,
	lastContext: string | undefined,
): string {
	return [
		"[CIRCUIT BREAKER — MANDATORY REFLECTION]",
		"",
		`${failureCount} consecutive attempts have failed. A further attempt is BLOCKED`,
		"until you complete the structured reflection below.",
		"",
		lastContext ? `Last failure context: ${lastContext.slice(0, 300)}` : "",
		"",
		"You are in a failure loop. Write each section explicitly.",
		"",
		"─── R1: Blind Spots — What have I NOT considered? ───",
		"List aspects of the problem you have NOT yet examined.",
		"For each: why was it overlooked? Could it be the root cause?",
		"",
		"─── R2: Method Inventory — What approaches exist? ───",
		"Enumerate ALL available methods (minimum 3):",
		"• What you tried and WHY it failed (be specific, not \"it didn't work\")",
		"• What alternatives you have NOT tried",
		"• For each alternative: expected outcome, risk level",
		"",
		"─── R3: Sequence — Am I operating in the right order? ───",
		"What is the correct diagnostic sequence for this problem type?",
		"Did you skip steps or act out of order?",
		"What is the proper sequence going forward?",
		"",
		"─── R4: Causal Chain — Root cause or symptom? ───",
		"Trace: Observed symptom → [cause] → [cause] → Root cause",
		"Are you fixing a symptom or the root cause?",
		"If a symptom: what IS the root cause?",
		"",
		"─── R5: Constraints — What limits the solution space? ───",
		"List ALL applicable constraints:",
		"• Technical (language, framework, compatibility)",
		"• Business (uptime, data integrity)",
		"• Project (C-01 no source modification, HB-02 php7.4, etc.)",
		"Which constraints did your failed attempts violate?",
		"",
		"After reflection, propose a REVISED approach:",
		"1. What specifically will be DIFFERENT from previous attempts",
		"2. Why this addresses the ROOT CAUSE, not the symptom",
		"3. What verification will confirm success",
		"",
		"If you cannot produce a viable revised approach, ESCALATE to the",
		"user — do not attempt another fix blindly.",
	].join("\n")
}
