export function buildCognitiveGatePrompt(): string {
	return [
		"[COGNITIVE GATE — FIVE-DIMENSION ANALYSIS REQUIRED]",
		"",
		"Your action was blocked. No structured system analysis was detected in this session.",
		"",
		"Before any diagnostic or corrective action, you MUST complete the following analysis.",
		"Write each section explicitly — do not skip or abbreviate.",
		"",
		"─── D1: System Identity ───",
		"What system is involved? What business domain does it serve?",
		"What is its primary function and who are its end users?",
		"→ Consult: AGENTS.md project overview, _meta/knowledge/glossary.md",
		"",
		"─── D2: System Composition ───",
		"What components, services, databases, caches, and message queues are involved?",
		"What third-party integrations exist?",
		"Map the dependency chain relevant to this problem.",
		"→ Consult: _meta/knowledge/project-index.md, architecture docs",
		"",
		"─── D3: Operational Flow ───",
		"Trace the end-to-end data/control flow for the relevant process.",
		"Pinpoint WHERE in this flow the problem manifests.",
		"Identify what is upstream (inputs) and downstream (consumers).",
		"→ Consult: business flow docs, source code trace",
		"",
		"─── D4: Deployment & Configuration ───",
		"Where and how is this deployed? (server, port, process manager)",
		"What config files, credentials, and access points are relevant?",
		"What deployment constraints apply?",
		"→ Consult: _meta/deployment/, credentials-and-infra.md",
		"",
		"─── D5: Impact Scope ───",
		"What is the primary subject of this problem?",
		"Which modules are DIRECTLY affected?",
		"Which are INDIRECTLY affected via dependency chains?",
		"What is the blast radius if the proposed fix fails?",
		"",
		"After completing all five dimensions, deliver three items:",
		"1. DIAGNOSIS — what is wrong, traced to the dimension that revealed it",
		"2. APPROACH — what you will do, traced to why it is correct",
		"3. VERIFICATION — how you will confirm the fix succeeded",
		"",
		"Your next action will be unblocked after this analysis is written.",
	].join("\n")
}
